// <auto-generated />
using System;
using AccountingRazor2021.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountingRazor2021.Persistence.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20211101074032_InitialCreate6")]
    partial class InitialCreate6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountingRazor2021.Domain.DataAccount", b =>
                {
                    b.Property<Guid>("DataAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Account");

                    b.Property<string>("Aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("Depth");

                    b.Property<string>("Kelompok")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Kelompok");

                    b.Property<string>("KodeAccount")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("KodeAccount");

                    b.Property<int?>("Lft")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("Lft");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NormalPos")
                        .HasColumnType("int")
                        .HasColumnName("NormalPos");

                    b.Property<string>("Parent")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Parent");

                    b.Property<int?>("Rgt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("Rgt");

                    b.HasKey("DataAccountId");

                    b.ToTable("DataAccount");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataBuktiTransaksi", b =>
                {
                    b.Property<Guid>("DataBuktiTransaksiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("NoBukti")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoBukti");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("datetime")
                        .HasColumnName("TanggalInput");

                    b.Property<int>("TipeJournalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("money")
                        .HasColumnName("Total");

                    b.Property<string>("ValidateBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValidateBy");

                    b.Property<DateTime>("ValidatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ValidatedDate");

                    b.HasKey("DataBuktiTransaksiId");

                    b.ToTable("DataBuktiTransaksi");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataJournalDetails", b =>
                {
                    b.Property<Guid>("DataJournalDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataJournalHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("money")
                        .HasColumnName("Debit");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("Keterangan");

                    b.Property<decimal?>("Kredit")
                        .HasColumnType("money")
                        .HasColumnName("Kredit");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SaldoAwal")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("datetime2");

                    b.HasKey("DataJournalDetailsId");

                    b.ToTable("DataJournal");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataJournalHeader", b =>
                {
                    b.Property<Guid>("DataJournalHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aktif")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Aktif");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("NoBuktiJournal")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("NoBuktiJournal");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipeJournalId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRupiah")
                        .HasColumnType("money");

                    b.Property<string>("UserInput")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UserInput");

                    b.Property<DateTime?>("Validasi")
                        .HasColumnType("datetime")
                        .HasColumnName("Validasi");

                    b.Property<string>("ValidasiOleh")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ValidasiOleh");

                    b.HasKey("DataJournalHeaderId");

                    b.ToTable("DataJournalHeader");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataPeriode", b =>
                {
                    b.Property<Guid>("DataPeriodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aktif")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("IsAktif");

                    b.Property<DateTime>("Berakhir")
                        .HasColumnType("datetime")
                        .HasColumnName("Berakhir");

                    b.Property<DateTime>("Mulai")
                        .HasColumnType("datetime")
                        .HasColumnName("Mulai");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserInput")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserInput");

                    b.HasKey("DataPeriodeId");

                    b.ToTable("DataPeriode");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataSaldoAwal", b =>
                {
                    b.Property<Guid>("DataSaldoAwalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Debet")
                        .HasColumnType("money")
                        .HasColumnName("Debet");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("money")
                        .HasColumnName("Kredit");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Saldo")
                        .HasColumnType("money")
                        .HasColumnName("Saldo");

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2021, 11, 1, 14, 40, 31, 633, DateTimeKind.Local).AddTicks(7487))
                        .HasColumnName("TanggalInput");

                    b.HasKey("DataSaldoAwalId");

                    b.ToTable("DataSaldoAwal");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.DataSaldoHarian", b =>
                {
                    b.Property<Guid>("DataSaldoHarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Debet")
                        .HasColumnType("money")
                        .HasColumnName("Debet");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("money")
                        .HasColumnName("Kredit");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Saldo")
                        .HasColumnType("money")
                        .HasColumnName("Saldo");

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2021, 11, 1, 14, 40, 31, 647, DateTimeKind.Local).AddTicks(2781))
                        .HasColumnName("TanggalInput");

                    b.HasKey("DataSaldoHarianId");

                    b.ToTable("DataSaldoHarian", "Accounting");
                });

            modelBuilder.Entity("AccountingRazor2021.Domain.TipeJournal", b =>
                {
                    b.Property<Guid>("TipeJournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KodeJournal")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NamaJournal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NamaJournal");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("TipeJournalId");

                    b.ToTable("TipeJournal");

                    b.HasData(
                        new
                        {
                            TipeJournalId = new Guid("df8c7140-25b9-4e9c-add9-c96c36e5c759"),
                            KodeJournal = "JU",
                            NamaJournal = "JURNAL UMUM",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("e4bc3f28-23f4-4a4e-9c81-68361304f0b1"),
                            KodeJournal = "JPMB",
                            NamaJournal = "JURNAL PEMBELIAN",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("f0041d67-bd93-4395-b5d2-6835baed4d2d"),
                            KodeJournal = "JPJ",
                            NamaJournal = "JURNAL PENJUALAN",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("3670b377-8bcc-4f86-a56a-420680f22828"),
                            KodeJournal = "JPNK",
                            NamaJournal = "JURNAL PENERIMAAN KAS",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("a5dff7df-3516-48cd-9f68-f250f76cffcb"),
                            KodeJournal = "JPGNK",
                            NamaJournal = "JURNAL PENGELUARAN KAS",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("0414c9c7-daf8-4a74-91e8-8400f33c220f"),
                            KodeJournal = "JPEY",
                            NamaJournal = "JURNAL PENYESUAIAN",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("1ce224d8-cc89-432e-91ed-5dbb40284870"),
                            KodeJournal = "JPMBK",
                            NamaJournal = "JURNAL PEMBUKA",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("c3e2c26d-7bb3-4302-b0ce-b19043a9fc6b"),
                            KodeJournal = "JPNTP",
                            NamaJournal = "JURNAL PENUTUP",
                            NoUrutId = 0
                        },
                        new
                        {
                            TipeJournalId = new Guid("3e68ada8-a02b-41a2-89b4-bcac5d7ac05f"),
                            KodeJournal = "JPMBLK",
                            NamaJournal = "JURNAL PEMBALIK",
                            NoUrutId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
